### ISSUE TITLE
Add support for rubocop-0.50

### ISSUE THREAD

**Issue by deivid-rodriguez** [codeclimate/codeclimate-rubocop#107]
Rubocop 0.50 [has been released](https://rubygems.org/gems/rubocop/versions/0.50.0). It'd be great to get support in the official engine, via a channel, or even by fixing #93 :)

Thanks a lot!

**Comment by toddmazierski** [comment]
Thanks for the heads up, @deivid-rodriguez! We'll get on this.

**Comment by apanzerj** [comment]
@toddmazierski any updates?

**Comment by katwchen** [comment]
Hi @apanzerj  
@pointlessone is working on this now. he was on vacation last week, just came back. he will keep us posted here on his progress!

**Comment by apanzerj** [comment]
Sweet. Thanks!

**Comment by dblandin** [comment]
Hey all, looks like a `rubocop-0-50` channel is now available!

```yaml
engines:
  rubocop:
    enabled: true
    channel: rubocop-0-50
```

Thanks for your patience 👍

**Comment by dblandin** [comment]
Going to go ahead and close this issue but let us know if you run into any issues enabling and running the engine. Thanks!
