### ISSUE TITLE
Add support for rubocop-0.51

### ISSUE THREAD

**Issue by deivid-rodriguez** [codeclimate/codeclimate-rubocop#109]
Rubocop 0.51 [has been released](https://github.com/bbatsov/rubocop/releases/tag/v0.51.0). It'd be great to get support in the official engine, via a channel, or even by fixing #93 :)

Thanks a lot!

**Comment by maxjacobson** [comment]
Thanks for the head's up @deivid-rodriguez! I'm going to get this into our product backlog today.

**Comment by dbusanello** [comment]
Hello @maxjacobson

Is this issue fixed by https://github.com/codeclimate/codeclimate-rubocop/pull/110?

**Comment by maxjacobson** [comment]
Hi @dbusanello --

It means it's close. That work created the channel, but we still need to deploy it to codeclimate.com and the CLI.

@pointlessone, will you please update us on this issue once that's completed?

**Comment by matheuslc** [comment]
Is this issue fixed? Are 0.51 channel deployed to CC already?

**Comment by maxjacobson** [comment]
Yep, apologies for not updating this issue, but this went out to codeclimate.com and the CLI 9 days ago.

Just specify the `rubocop-0-51` channel (https://docs.codeclimate.com/docs/engine-channels)

**Comment by eebs** [comment]
Hi @maxjacobson, I'm not sure it did, when I run `codeclimate analyze` locally, I get the following error:

```
error: (CC::Analyzer::Container::ImageRequired) Unable to find an image for rubocop:rubocop-0-51. Available channels: ["stable", "cache-support", "rubocop-0-42", "rubocop-0-46", "rubocop-0-48", "rubocop-0-49", "rubocop-0-50"]
```

I'm using 0.68.0 of the CLI, and `brew update && brew upgrade codeclimate` says I'm up to date.

I don't see a new [release of the CLI](https://github.com/codeclimate/codeclimate/releases) that includes this fix either.

**Comment by maxjacobson** [comment]
Yep, good point. Looks like we didn't cut a new CLI release after adding this channel. Standby, I'll do that now.

**Comment by maxjacobson** [comment]
Fresh off the presses: https://github.com/codeclimate/codeclimate/releases/tag/v0.69.0

**Comment by eebs** [comment]
Thanks a ton!
