### ISSUE TITLE
Rubocop 0.52.1

### ISSUE THREAD

**Issue by deivid-rodriguez** [codeclimate/codeclimate-rubocop#115]
Rubocop 0.52.1 was [released](https://github.com/bbatsov/rubocop/releases/tag/v0.52.1) with many bug fixes, it'd be nice to get images updated.

Thanks! :)

**Comment by wilson** [comment]
In progress: https://github.com/codeclimate/codeclimate-rubocop/pull/116

**Comment by deivid-rodriguez** [comment]
Wow, that was fast, thanks! Currently seems available in the CLI but not yet in codeclimate.com, is that right?

**Comment by wilson** [comment]
Unless I did something wrong (totally possible), 0.52.1 should now be on the "stable" and "rubocop-0-52" channels. The CLI does have a different way of noticing updates, but both sides of the story should now be updated.

**Comment by wilson** [comment]
Oh yes I did miss a step. I'll report back when it's actually available as the default on the web.

**Comment by deivid-rodriguez** [comment]
Thanks! :heart:

**Comment by wilson** [comment]
I ended up having to debug some of the release tooling; sorry for the delay. This should now be the default stable Rubocop on both the web and the CLI sides.

**Comment by deivid-rodriguez** [comment]
Thanks, seems fixed now! :heart: 

Closing!
