### ISSUE TITLE
Rubocop 0.53.0 Released

### ISSUE THREAD

**Issue by snowblink** [codeclimate/codeclimate-rubocop#118]
Please could we make rubocop 0.53.0 available as a channel?

**Comment by monfresh** [comment]
Any idea when this might become available? Thanks!

**Comment by GeorgeKaraszi** [comment]
Hate to be that guy, but is there any update?

**Comment by andyw8** [comment]
I noticed there's now's a channel for 0.54.

**Comment by wfleming** [comment]
Apologies for the delay here. We do now have RuboCop 0.54 in a channel (you  can use it with something like the config below in your `.codeclimate.yml`).

```
plugins:
  rubocop:
    channel: rubocop-0-54
```

Does anyone here need 0.53 specifically, or would it be better for folks to jump to 0.54 and skip 0.53? Thanks.

**Comment by stefanahman** [comment]
@wfleming That works, but you still get some faulty errors if you use a different locally vs the one CodeClimate uses. `0.59.1` is available now but the latest are `0.58.0` (https://github.com/codeclimate/codeclimate-rubocop/branches/all?utf8=%E2%9C%93&query=channel%2Frubocop)

Maybe this could be scripted for automatic updates?
