### ISSUE TITLE
Rubocop 0.55.0 release

### ISSUE THREAD

**Issue by artplan1** [codeclimate/codeclimate-rubocop#121]
Hi!

Can you release rubocop 0.55.0 available as a channel?

https://github.com/bbatsov/rubocop/releases/tag/v0.55.0

Thanks.

**Comment by kimyu92** [comment]
And now rubocop 0.57.0. https://github.com/rubocop-hq/rubocop/releases/tag/v0.57.0

![ :shipit: ](https://i.imgur.com/KETBnSQ.gif)

**Comment by ale7714** [comment]
Hi everyone! 👋 Thank you for using Code Climate and writing about this. We included this in our planning board and we will be following up when we have ready a new rubocop release.

**Comment by katwchen** [comment]
We are working on this this week.

**Comment by wilson** [comment]
Rubocop versions 0.55.0, 0.56.0, and 0.57.2 are now supported.

New channels:
- `rubocop-0-55`
- `rubocop-0-56`
- `rubocop-0-57`

Updated items:
- `codeclimate` gem
- `builder` engine registry
- `codeclimate-rubocop` channel branches

The `stable` channel still refers to v0.52.1, pending discussion of which version should be chosen next.
