### ISSUE TITLE
Notifications of new releases?

### ISSUE THREAD

**Issue by andyw8** [codeclimate/codeclimate-rubocop#130]
I'm happy to see there are branches (engine channels) being regularly added for new releases of RuboCop. But even though I subscribe to the repo, there seems to be no mechanism for GitHub to send notifications about the new branches.

Would it be possible to create a new issue corresponding to each new release, to serve as an announcement?

**Comment by janos** [comment]
Since GitHub does not have the option to be notified only about new releases, I’ve created a service that does exactly this. Notifications are sent out to your email and/or Slack account and it even has several filtering options, including with using regex: https://newreleases.io.

**Comment by andyw8** [comment]
Closing since GitHub now has an option to watch for new releases.
