### ISSUE TITLE
Rubocop 0.59

### ISSUE THREAD

**Issue by dgilperez** [codeclimate/codeclimate-rubocop#132]
rubocop 0.59.0, 0.59.1 and 0.59.2 are out there. Could you please add support as a rubocop-0.59 channel for that?

**Comment by dgilperez** [comment]
@ale7714 sorry if I'm being a bit pushy here. We're using 0.59 in production and would definitely like it to work in our regular integration workflow - do you have any estimated time for this?

**Comment by ale7714** [comment]
@dgilperez thank you for the ping. I'll add this to our planning board and update you as soon as is released.

**Comment by ale7714** [comment]
@dgilperez 👋thank you for your patience! channel `rubocop-0-59` is available.
