### ISSUE TITLE
rubocop-0.59 branch has an older rubocop-rspec

### ISSUE THREAD

**Issue by andyw8** [codeclimate/codeclimate-rubocop#134]
Hi, it seems the latest branch is using an older version of rubocop-rpsec.

https://github.com/codeclimate/codeclimate-rubocop/blob/channel/rubocop-0-58/Gemfile.lock#L52
vs
https://github.com/codeclimate/codeclimate-rubocop/blob/channel/rubocop-0-59/Gemfile.lock#L52

(The latest release of rubocop-rspec is 1.30.0: https://rubygems.org/gems/rubocop-rspec/versions/1.30.0)

@ale7714

**Comment by ale7714** [comment]
@andyw8 thank you for the ping! rubocop-0-59 updated.
