### ISSUE TITLE
channel rubocop-0-62 errors with Unknown Ruby version 2.6

### ISSUE THREAD

**Issue by efueger** [codeclimate/codeclimate-rubocop#152]
Plugin's new channels for Rubocop (0-60, 0-61, 0-63) work as expected.
- 0-62 errors with **`Unknown Ruby version 2.6 found in TargetRubyVersion`**

Tested here: https://github.com/efueger/alonetone/pull/2

Check Admin repo: 5c4f290ef8398334990034bf PR 2

**Comment by larkinscott** [comment]
Just merged in a fix for this here: https://github.com/codeclimate/codeclimate-rubocop/pull/153

**Comment by hovancik** [comment]
Hey @larkinscott , I am still seeing error in CC: 

https://codeclimate.com/github/hovancik/little_expense_manager/pull/45

```
/usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/processed_source.rb:129:in `parser_class': Unknown Ruby version: 2.6 (ArgumentError)
	from /usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/processed_source.rb:137:in `create_parser'
	from /usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/processed_source.rb:94:in `parse'
	from /usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/processed_source.rb:36:in `initialize'
	from /usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/processed_source.rb:17:in `new'
	from /usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/processed_source.rb:17:in `from_file'
	from /usr/src/app/lib/cc/engine/source_file.rb:27:in `processed_source'
	from /usr/src/app/lib/cc/engine/source_file.rb:14:in `inspect'
	from /usr/src/app/lib/cc/engine/rubocop.rb:35:in `block (2 levels) in run'
	from /usr/src/app/lib/cc/engine/rubocop.rb:29:in `each'
	from /usr/src/app/lib/cc/engine/rubocop.rb:29:in `block in run'
	from /usr/src/app/lib/cc/engine/rubocop.rb:28:in `chdir'
	from /usr/src/app/lib/cc/engine/rubocop.rb:28:in `run'
	from /usr/src/app/bin/codeclimate-rubocop:17:in `<main>'
```

**Comment by wfleming** [comment]
It looks like Jan found the solution to his problem, but I'm going to leave a note here in case anyone else has a similar problem and stumbles across this issue.

We only added the support for Ruby 2.6 the `rubocop-0-62` channel and newer, so if anybody is still using a channel of our `rubocop` engine for a version earlier than 0.62 and hits a similar error, the solution is to change your `.codeclimate.yml` or `.codeclimate.json` to specify a newer channel. (At the time I'm writing this, the most recent version we support on a channel is `rubocop-0-74`.

**Comment by hovancik** [comment]
No worries, support helped me ;]
