### ISSUE TITLE
Rubocop 0.67 release

### ISSUE THREAD

**Issue by mnordin** [codeclimate/codeclimate-rubocop#164]
Rubocop had (yet) another minor update to [0.67](https://github.com/rubocop-hq/rubocop/releases/tag/v0.67.0).

Could you add support for it? Thanks!

**Comment by Mange** [comment]
Any update on this? Due to #165 we cannot run Codeclimate anymore on our config because it's based on the 0.67 branch and `require`s `rubocop-performance`.

Can we help in any way to get this out soon?

**Comment by pean** [comment]
To clarify, `rubocop` 0.68 will require [`rubocop-performance`](https://github.com/rubocop-hq/rubocop-performance), but as warning as been added in 0.67.

**Comment by wfleming** [comment]
Thanks for your patience. We've released a new `rubocop-0-67` channel to support this release. To use it with the CLI or codeclimate.com, configure RuboCop in your `.codeclimate.yml` like so:

```
plugins:
  rubocop:
    enabled: true
    channel: rubocop-0-67
```
