### ISSUE TITLE
Performance cops moving to own gem

### ISSUE THREAD

**Issue by agirling** [codeclimate/codeclimate-rubocop#165]
Per [ rubocop PR #6890](https://github.com/rubocop-hq/rubocop/pull/6890), performance cops will be moved to the `rubocop-performance` gem.

Analysis is currently breaking due to this change:

```
/usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:122:in `require': cannot load such file -- rubocop-performance (LoadError)
```

**Comment by wfleming** [comment]
@agirling I think your configuration is using the `stable` channel of our RuboCop plugin, which is runs RuboCop 0.52.1, so the performance cops are still built-in. I suspect you added a `require: rubocop-performance` to your `.rubocop.yml`, but you don't need that for Code Climate and it's inclusion is causing the problem. I'd suggest removing that from your `.rubocop.yml` for now.

RuboCop only just made this change, and haven't released a version including this change yet. When we release a new channel of our plugin for that eventual RuboCop version we'll include the new `rubocop-performance` gem in the build and then it'll be available if you switch to that channel after it's released.

**Comment by agirling** [comment]
@wfleming spot on, I did add the require to my `.rubocop.yml`.  I'll remove that for the time being.  Thank you for the background and detail.

**Comment by wfleming** [comment]
Closing for now since this doesn't impact any currently released versions of our plugin. It'll come up when we need to release a new channel for a later rubocop release.

**Comment by RicardoTrindade** [comment]
I'm getting the same issue, now that rubocop 0.68 was released, any news on this ?

**Comment by wfleming** [comment]
We haven't released a channel supporting 0.68 yet (when we do #167 would be the issue to watch).

We do have a channel for 0.67 (see #164), and that channel does support the gem, so you could use that in the meantime.

**Comment by alaxalves** [comment]
Any updates on this?

**Comment by corsonknowles** [comment]
Can we get an update on this, please? @wfleming

**Comment by ElliotVilhelm** [comment]
`gem install rubocop-performance`?

**Comment by katelovescode** [comment]
What about for later versions like 1-19 and 1-18-3?
