### ISSUE TITLE
Rubocop 0.70 released

### ISSUE THREAD

**Issue by modosc** [codeclimate/codeclimate-rubocop#169]
~~https://github.com/rubocop-hq/rubocop/releases/tag/v0.69.0~~

https://github.com/rubocop-hq/rubocop/releases/tag/v0.70.0

**Comment by stefanahman** [comment]
Why isn't this automated?

**Comment by Mange** [comment]
> Why isn't this automated?

…or using the version from the `Gemfile` of the project.

I suspect it has to do with how the report is digested and used in the interface, but I can only guess.

**Comment by modosc** [comment]
alternately - if bandwidth is an issue on the codeclimate side why not make this a community maintained image?

**Comment by Fryguy** [comment]
> Why isn't this automated?

Likely because rubocop doesn't follow SemVer and constantly breaks things from minor version to minor version, such as changing cop names.

**Comment by kbrock** [comment]
Also, all channel names are hardcoded in the base code climate config [[engine file]](https://github.com/codeclimate/codeclimate/blob/master/config/engines.yml#L201), so it is a little more of a change than a simple "just automate it"

**Comment by marcelotoledo5000** [comment]
I tried to update, [but I had a problem](https://circleci.com/gh/codeclimate/codeclimate-rubocop/454), if can anyone help me to fix it, after this, anyone needs to accept the PR... I don't know what happened with the last PR before mine, is OK, but was not accepted yet.

https://github.com/codeclimate/codeclimate-rubocop/pull/171

**Comment by Mange** [comment]
NOTE: This issue was changed to ask for 0.70 instead of 0.69.

(This comment should also trigger a notification for any subscribers to this issue.)

**Comment by marcelotoledo5000** [comment]
I still have a problem with this test...

https://circleci.com/gh/codeclimate/codeclimate-rubocop/456?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link

Here: https://github.com/codeclimate/codeclimate-rubocop/pull/172

Can anyone help me?

**Comment by modosc** [comment]
looks like this is live now?

**Comment by Mange** [comment]
Sure looks like it. I suggest closing this issue.
https://github.com/codeclimate/codeclimate-rubocop/compare/channel/rubocop-0-69...channel/rubocop-0-70

**Comment by pean** [comment]
> looks like this is live now?

Just in time for the 0.71 release..
