### ISSUE TITLE
rubocop-performance missing in 0.68+

### ISSUE THREAD

**Issue by granth** [codeclimate/codeclimate-rubocop#187]
The `rubocop-performance` gem is included in the `rubocop-0-67` channel, but not `rubocop-0-68` and up.

https://github.com/codeclimate/codeclimate-rubocop/blob/c459430a62401a36ed926df7649c4baa983e8a79/Gemfile#L9-L12
https://github.com/codeclimate/codeclimate-rubocop/blob/94f870a1775bb49adfdeebf7f68803cb9ad2433f/Gemfile#L9-L11

**Comment by filipesperandio** [comment]
https://github.com/codeclimate/codeclimate-rubocop/pull/189
https://github.com/codeclimate/codeclimate-rubocop/pull/191
https://github.com/codeclimate/codeclimate-rubocop/pull/192
https://github.com/codeclimate/codeclimate-rubocop/pull/194
