### ISSUE TITLE
Version 0.75 is released

### ISSUE THREAD

**Issue by Mange** [codeclimate/codeclimate-rubocop#209]
I do hope #93 could get implemented some day, but until then, here's yet another reminder issue of a new Rubocop version. :smile:

**Comment by Mange** [comment]
Any update on this?

**Comment by ur5us** [comment]
@Mange [Available channels](https://github.com/codeclimate/codeclimate-rubocop/branches/all?utf8=%E2%9C%93&query=channel%2Frubocop)

**Comment by davehenton** [comment]
Thanks @ur5us !

@magec Rubocop 0.75 (as well as 0.76) is now available in Code Climate. 

To [use one of these newer versions](https://docs.codeclimate.com/docs/rubocop#section-using-rubocops-newer-versions), you'll need to commit a `.codeclimate.yml` with the following configuration:

```
plugins:
  rubocop:
    enabled: true
    channel: rubocop-0-75
```

**Comment by filipesperandio** [comment]
Fixed by https://github.com/codeclimate/codeclimate-rubocop/pull/211
