### ISSUE TITLE
Project permissions

### ISSUE THREAD

**Issue by andyw8** [codeclimate/codeclimate-rubocop#24]
I opened a PR (#23) but I'm unable to see the CodeClimate report on it.

When I visit https://codeclimate.com/repos/55ccc68e6956802d030012f3/compare I'm prompted to sign-in, then I get a 422 error.

**Comment by pbrisbin** [comment]
Hey @andyw8 sorry about this, a lot of our OSS repos were added to CC while they were still private and need to be re-added as OSS. I'll try to do that soon.

**Comment by jpignata** [comment]
I re-added this as an OSS project. Should be all set.
