### ISSUE TITLE
Rubocop 0.87 channel is not working

### ISSUE THREAD

**Issue by severin** [codeclimate/codeclimate-rubocop#244]
The documentation links to this page for supported channels: https://github.com/codeclimate/codeclimate-rubocop/branches/all?utf8=%E2%9C%93&query=channel%2Frubocop and it includes 0.87...

However, trying to use that channel results in

```
Channel rubocop-0-87 not found for rubocop, available channels: ["stable", "cache-support", "rubocop-0-42", "rubocop-0-46", "rubocop-0-48", "rubocop-0-49", "rubocop-0-50", "rubocop-0-51", "rubocop-0-52", "rubocop-0-54", "rubocop-0-55", "rubocop-0-56", "rubocop-0-57", "rubocop-0-58", "rubocop-0-59", "rubocop-0-60", "rubocop-0-61", "rubocop-0-62", "rubocop-0-63", "rubocop-0-64", "rubocop-0-66", "rubocop-0-65", "rubocop-0-67", "rubocop-0-68", "rubocop-0-69", "rubocop-0-70", "rubocop-0-71", "rubocop-0-72", "rubocop-0-73", "rubocop-0-74", "rubocop-0-75", "rubocop-0-76", "rubocop-0-77", "rubocop-0-78", "rubocop-0-79", "rubocop-0-80", "rubocop-0-81", "rubocop-0-82", "rubocop-0-83", "rubocop-0-84", "rubocop-0-85", "rubocop-0-86"]
```

(https://codeclimate.com/repos/5e5d099cf7ab35016200ddaa/builds/381)

**Comment by filipesperandio** [comment]
Channel 87 is not yet released - https://github.com/codeclimate/codeclimate-rubocop/issues/243
The branch is opened pointing to v86 - help is wanted in order to solve the items described in the issue, we will eventually get to it, though.

**Comment by filipesperandio** [comment]
This is a fix https://github.com/codeclimate/codeclimate-rubocop/pull/245
We will be releasing it next week.
