### ISSUE TITLE
Bump RuboCop version?

### ISSUE THREAD

**Issue by utkarsh2102** [codeclimate/codeclimate-rubocop#254]
Hi,

https://github.com/codeclimate/codeclimate-rubocop/blob/dba3b70ec3042e8ccfb7848e3dfe709b2754380b/Gemfile#L9

It appears that the RuboCop version here is very old. It'd be nice if we could bump the version?
I'd be happy to send a PR if so? 😄 

CC: @filipesperandio :)

**Comment by krzysiek1507** [comment]
You can use channel if you want to have a specific version. The newest is currently `rubocop-0-89`, but I'm not sure if it is available on CodeClimate. `rubocop-0-88` is available for sure.

**Comment by filipesperandio** [comment]
@utkarsh2102: What @krzysiek1507 said.

We may eventually update the master branch (stable channel) to something more recent, till we do, we suggest using the channels for specific versions. `rubocop-0-89`  was already released.
