### ISSUE TITLE
Rubocop 1.4.1

### ISSUE THREAD

**Issue by sdrioux** [codeclimate/codeclimate-rubocop#265]
1.4.1 is listed as a supported channel here: https://github.com/codeclimate/codeclimate-rubocop/branches/all?utf8=%E2%9C%93&query=channel%2Frubocop.  However, it does not appear to be working for me.  Is this a known issue?

**Comment by noelia-lencina** [comment]
Hi, @sdrioux - Sorry for the confusion. We have the intention of adding support to rubocop 1.4.1 but that's still in the works and blocked by some updated that need to be done in other repos. There's this draft PR https://github.com/codeclimate/codeclimate-rubocop/pull/263 in case you are interested in having a look there.
I deleted the branch to avoid more confusion and we will create it again once we are in ready to really add the support. Thanks!
