### ISSUE TITLE
Update rubocop-rails

### ISSUE THREAD

**Issue by BrianHawley** [codeclimate/codeclimate-rubocop#291]
For rubocop 1.12.1 and earlier, which support Ruby 2.4, update rubocop-rails to version 2.9.1, the last version supporting Ruby 2.4.

For later rubocop versions, update rubocop-rails to 2.11.2 (the latest as of the time of writing).

You might want to avoid updating rubocop-rails in channels that are already in use, but rubocop-1-12-1 and later should be OK to update because of #289 (PRs #281, #282, #283, #284, #285, #286, #287, #288).

**Comment by BrianHawley** [comment]
Darn, this needed to happen before all of those PRs were merged, but I didn't write the issue in time.

**Comment by fede-moya** [comment]
@BrianHawley 😅 , WDYT of just updating `rubocop-rails` to 2.11.2 on the rubocop's latest version ? and update the previous ones only if needed ?

**Comment by BrianHawley** [comment]
Doesn't help me, because I'm stuck on Ruby 2.4 for now. Still, it could help people who are able to use the latest version.

**Comment by fede-moya** [comment]
>  So, if you updated channels 1-12-1 and 1-18-3, that would do.
Okay. I think we can do that then.

**Comment by BrianHawley** [comment]
Closed by PRs #292 and #294.
