### ISSUE TITLE
Update rubocop-rspec

### ISSUE THREAD

**Issue by BrianHawley** [codeclimate/codeclimate-rubocop#293]
Update rubocop-rspec to 2.2.0 In channel 1-12-1, because of Ruby 2.4 compatibility. Update rubocop-rspec to 2.4.0 in channel 1-18-3.

Only mentioned those specific channels because they're not yet released.

**Comment by BrianHawley** [comment]
This might be considered a dup of #271.

**Comment by fede-moya** [comment]
Feel  free to open prs for `rubocop-rspec`, I won't be performing that update this week but I could merge work.

**Comment by BrianHawley** [comment]
@fede-moya I opened the PRs to get channels 1-12-1 and 1-18-3 up to date.

**Comment by BrianHawley** [comment]
@fede-moya as with the rubocop-rails update issue, the channel that I personally need the updates for the most is 1-12-1, so PR #295 is the critical one for me to get in there.

**Comment by fede-moya** [comment]
@BrianHawley done ! Thank you for opening prs 👏🏼
