### ISSUE TITLE
Support Rubocop 1.19.0

### ISSUE THREAD

**Issue by teoljungberg** [codeclimate/codeclimate-rubocop#298]
Yesterday (12/8 2021) Rubocop cut release 1.19.0. We'd like it supported on CodeClimate.

I'll happily help submit a patch to support it, but from my spelunking I found [bin/newver], but that requires access to be able to upload the Docker image. In short, it doesn't look like I can help submit an update for this.

We'd very much appreciate a new cut release for this version :) Thanks!

[bin/newver]: https://github.com/codeclimate/codeclimate-rubocop/blob/722a50ac0152f20617ea3d0fca587194e4671664/bin/newver

**Comment by timlkelly** [comment]
Hey, @teoljungberg 1.20.0 and 1.21.0 are available now. I skipped 1.19.0 because 1.20.0 was out when I last updated.

**Comment by teoljungberg** [comment]
Thanks!
