### ISSUE TITLE
# rubocop: comments ignored?

### ISSUE THREAD

**Issue by coteyr** [codeclimate/codeclimate-rubocop#40]
According to https://github.com/bbatsov/rubocop I should be able to use something like 

> \# rubocop:disable Style/AvoidFor

or 

> \# rubocop:disable all
> [...]
> \# rubocop:enable all

to skip a metric via comment in source code. For some reason I can't get this to work with the code climate CLI. Is there some config file or setting that I am missing?

**Comment by coteyr** [comment]
Or I could be insane. It could be that.

**Comment by ABaldwinHunter** [comment]
greetings @coteyr.

I don't doubt your sanity ;)

In some older versions, the CLI didn't properly respect rubocop's inline comments. That issue should [be fixed](https://github.com/codeclimate/codeclimate-rubocop/commit/485cc0c652e45c835a1b50ffd1949826d21e3c76) now. 
 
Try running:
`brew update && brew upgrade codeclimate` (if using brew) to install the latest version of codeclimate. Then add the `rubocop` engine to your `.codeclimate.yml` and run `codeclimate engines:install`. 

As a shortcut, you can also pull down the latest rubocop image from dockerhub with `docker pull codeclimate/codeclimate-rubocop`.

**Comment by coteyr** [comment]
Yeah it's working now.
