### ISSUE TITLE
Reports Time.now issues even on non-rails projects

### ISSUE THREAD

**Issue by nielsm** [codeclimate/codeclimate-rubocop#44]
I have a .rubocop.yml file in my project.   Running rubocop by hand doesn't show errors with Do not use `Time.now` without zone.  However, when run with codeclimate analyze, I get those errors.  Where is this cop being enabled (it is not enabled by default in Rubocop itself)

**Comment by jpignata** [comment]
Odd, the default configuration disables `Rails/TimeZone`, too. I couldn't reproduce this on my own – are you seeing this issue reported for every usage of `Time.now`? Can you share gist a small reproduction case?

**Comment by jpignata** [comment]
Hey @nielsm – is this still an issue for you?

**Comment by jpignata** [comment]
Please re-open if this is still occurring and we'll dig into it.
