### ISSUE TITLE
Allow specifying RuboCop version in config

### ISSUE THREAD

**Issue by segiddins** [codeclimate/codeclimate-rubocop#47]
Right now, bundler specifies the RuboCop version in its Makefile. If we were to switch to CodeClimate for running RuboCop, we'd need to be able to pin to the version of RuboCop our configuration is tuned for, and we don't have a `Gemfile.lock` that can be used to store that version for obvious reasons

**Comment by jpignata** [comment]
@segiddins We're working on this as a platform-wide change and expect to have something in place in the next several weeks. Thanks!

**Comment by jonahwh** [comment]
Is there any update on this? I can't seem to find any documentation about adjusting the versions of the analysis engines.

**Comment by briankung** [comment]
Not sure how many of those thumbs ups are from recent times, but I am interested, as well.

**Comment by andyw8** [comment]
For some engines possible specify a version using a Channel:

https://docs.codeclimate.com/v1.0/docs/engine-channel

For example, to use RuboCop v0.48 you can set `.codeclimate.yml` to be:

```
  rubocop:
    channel: rubocop-0-48
```

**Comment by segiddins** [comment]
@andyw8 that link seems to 404

**Comment by jonahwh** [comment]
[This page](https://docs.codeclimate.com/docs/rubocop) says that the available channels are just the [current branches](https://github.com/codeclimate/codeclimate-rubocop/branches/all?utf8=✓&query=channel%2F rubocop) which is by no means a comprehensive catalog of versions.

**Comment by andyw8** [comment]
@segiddins I've fixed the link (the last letter was missing).
