### ISSUE TITLE
Reports strings as mutable objects assigned to constants issue

### ISSUE THREAD

**Issue by nielsm** [codeclimate/codeclimate-rubocop#50]
Given the following constant:

SOMETHING = 'something'

Will generate this error:

Freeze mutable objects assigned to constants.

The help description says this should only apply to array or hashes.  Is it being too literal in considering a string an Array?  This only began with the 0.20 release of the CLI

**Comment by nielsm** [comment]
Incidentally, this was also noticed directly in Rubocop: https://github.com/bbatsov/rubocop/issues/2630

**Comment by GordonDiggs** [comment]
@nielsm That check is correct in referring to strings as well, depending on the ruby version. Before Ruby 2.3, strings were mutable (https://wyeworks.com/blog/2015/12/1/immutable-strings-in-ruby-2-dot-3). Looks like rubocop fixed this in 0.37.2, which we are using. Have you tried running `codeclimate engines:install` and then running `codeclimate analyze` again?

**Comment by nielsm** [comment]
Yes, just updated, which is when I started getting the errors

**Comment by wfleming** [comment]
Hi @nielsm,

I think this is just a case of RuboCop's help description not being exhaustive: strings do qualify as mutable objects for these cases. bbatsov/rubocop#2630 is specifically about supporting the new auto-frozen strings on Ruby 2.3, so it doesn't sound like that applies in your case. The previous version of rubocop we were using also reported `SOMETHING = 'something'` as a problem in my testing, so if you weren't seeing these reported before I think that was a bug that has now been fixed.

I'm going to go ahead & close this, but let me know if you have further questions.
