### ISSUE TITLE
Certain AllCops directives ignored

### ISSUE THREAD

**Issue by jpignata** [codeclimate/codeclimate-rubocop#59]
From https://github.com/codeclimate/codeclimate-rubocop/issues/39:

RuboCop's runner has some logic around selecting the right cops for a team based upon the configuration that our engine does not implement. We'll need to fix this in the engine to honor the StyleGuideCopsOnly attribute.

See https://github.com/bbatsov/rubocop/blob/1c0fb652cd3637ee779711206e17345b371e2731/lib/rubocop/runner.rb#L227 for what RuboCop does and https://github.com/codeclimate/codeclimate-rubocop/blob/277c6f88013d8f6f59a98d67662bddd9222109a0/lib/cc/engine/source_file.rb#L32 for what the Code Climate engine does.

**Comment by pbrisbin** [comment]
@jpignata do you know if this is still an issue? If so can you clarify a little bit? I'm having trouble following, maybe because your source links have drifted out of date.

**Comment by jpignata** [comment]
@pbrisbin I just took a quick glance and it does appear to still be an issue. I've updated the links to be evergreen. Basically, `mobilized_cop_classes` does some filtering that the engine doesn't.

**Comment by pbrisbin** [comment]
Thanks!

**Comment by jpignata** [comment]
Stale issue; closing.
