### ISSUE TITLE
Out of char range error.

### ISSUE THREAD

**Issue by gabrielgiordano** [codeclimate/codeclimate-rubocop#60]
Hey, I got this error while running rubocop engine in codeclimate:

![stack trace](http://i.imgur.com/LBnnLZN.png)

Apparently it was caused by a bug in Parser and they already [fixed](https://github.com/bbatsov/rubocop/issues/2833). But I notice in the [Gemfile.lock](https://github.com/codeclimate/codeclimate-rubocop/blob/master/Gemfile.lock#L17) that this repository still uses the old version. Could you bump the gem?

**Comment by beneti** [comment]
+1

**Comment by jpignata** [comment]
https://github.com/codeclimate/codeclimate-rubocop/pull/61 bumps parser and will be deployed shortly.
