### ISSUE TITLE
rubocop-rspec causing engine to crash

### ISSUE THREAD

**Issue by DMA57361** [codeclimate/codeclimate-rubocop#69]
I've just pulled one of our apps up to the newest version of rubocop, and am finding that this codeclimate rubocop engine is now crashing, even though running rubocop locally works fine.  

**In short: I think the version of rubocop-rspec in this engine needs updating.**

Reasons for my line of thinking:
- I have rubocop-rspec locally at 1.5.0 (most recent) and running rubocop locally works fine
- If I drop rubocop-rspec locally down to 1.4.0 (matching the engine) I get the same error locally
- I can work around the problem by commenting out the `require: rubocop-rspec`  in our .rubocop.yml file (allowing codeclimate to analyse without issue)

For info, I'm seeing the following:

```
$ codeclimate analyze -e rubocop
Starting analysis
Running rubocop: Done!
error: (CC::Analyzer::Engine::EngineFailure) engine rubocop:stable failed with status 1 and stderr
/usr/lib/ruby/gems/2.2.0/gems/rubocop-0.41.2/lib/rubocop/config_loader.rb:119:in `merge_with_default': undefined method `for_all_cops' for #<Hash:0x007fde11ca6510> (NoMethodError)
	from /usr/lib/ruby/gems/2.2.0/gems/rubocop-rspec-1.4.0/lib/rubocop/rspec/inject.rb:17:in `defaults!'
	from /usr/lib/ruby/gems/2.2.0/gems/rubocop-rspec-1.4.0/lib/rubocop-rspec.rb:9:in `<top (required)>'
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from /usr/lib/ruby/gems/2.2.0/gems/rubocop-0.41.2/lib/rubocop/config_loader_resolver.rb:16:in `block in resolve_requires'
	from /usr/lib/ruby/gems/2.2.0/gems/rubocop-0.41.2/lib/rubocop/config_loader_resolver.rb:12:in `each'
	from /usr/lib/ruby/gems/2.2.0/gems/rubocop-0.41.2/lib/rubocop/config_loader_resolver.rb:12:in `resolve_requires'
...
```

**Comment by pbrisbin** [comment]
Oh no!

Sorry about this. I wonder if there's a missing upper bound in the rubocop-rspec gem. Anyway, I'm working on upgrading right now.

**Comment by DMA57361** [comment]
Nice, that seems to be working for us. 👍
Thanks for the quick turn around.
