### ISSUE TITLE
Is it possible to ask Code Climate to run Rubocop with the -R flag?

### ISSUE THREAD

**Issue by monfresh** [codeclimate/codeclimate-rubocop#84]
Hi. We have Rails-specific cops defined in our .rubocop.yml, but Code Climate does not seem to run them. When I run `rubocop -R` locally, it reports offenses, but Code Climate does not. Is there a setting where we can tell Code Climate to use the `-R` flag?

**Comment by maxjacobson** [comment]
Hi @monfresh 

If you add the following to your `.rubocop.yml`, does Code Climate start picking up those issues?

```yaml
Rails:
  Enabled: true
```

**Comment by monfresh** [comment]
Yep. Was just about to post that. Thanks. Rubocop could do a better job of exposing that documentation. I ended up searching for `rails` in all of Code Climate's repos, then found `RunRailsCops: true`, which resulted in an error that told me to use `Rails: Enabled: true` instead.

**Comment by maxjacobson** [comment]
Heh, nice. Yea, I think that was the old name.

I was surprised not to see this config documented on [the rails cops page of the manual](http://rubocop.readthedocs.io/en/latest/cops_rails/) -- I bet they'd accept a PR explaining it there if you want to add it.
