### ISSUE TITLE
ignore inherit from .rubocop_todo.yml

### ISSUE THREAD

**Issue by Br3nda** [codeclimate/codeclimate-rubocop#86]
`.rubocop_todo.yml` is a standard filename to keep issues that need fixing, but haven't yet

https://github.com/bbatsov/rubocop/blob/master/manual/configuration.md#automatically-generated-configuration

It means CI can enforce rubocop on (most) new code while you're chipping away at historical code.

However, adding a .rubocop_todo.yml to a project causes Codeclimate to instantly jump the score up and consider every ignored issue as fixed. Projects jump from a 2.0 GPA to 3.9 with one commit.

Later when the issue are genuinely fixed, Codeclimate does not notice. the score does not change, and the contributor gets no glory.

I request codeclimate-rubocop learns to ignore (remove before analysis?) this exact line at the top of a .rubocop.yml
`inherit_from: .rubocop_todo.yml`

**Comment by wfleming** [comment]
Hi @Br3nda,

Thanks for the suggestion, but we don't think this is a direction we want to go
in right now for default behavior. In general, we think Code Climate engines
work best for people when they adhere as closely as possible to what the same
tool would do when you ran it locally without Code Climate. In the case you're
talking about, the `.rubocop_todo.yml` file is explicit configuration saying
that some RuboCop issues should be ignored, and we think it's best for this
engine to continue to respect that by default.

That said, this is behavior you can configure yourself today! You can move the
bulk of your RuboCop configuration to a separate file (e.g.
`.rubocop_codeclimate.yml`), and then change your `.rubocop.yml` to have no
actual configuration except inheriting from `.rubocop_codeclimate.yml` and
`.rubocop_todo.yml`, e.g.

```yaml
inherit_from: .rubocop_codeclimate.yml
inherit_from: .rubocop_todo.yml
```

Once you've done that, you can update your `.codeclimate.yml` to tell the
RuboCop engine to use `.rubocop_codeclimate.yml` for its configuration instead
of the default `.rubocop.yml`:

```yaml
engines:
  rubocop:
    enabled: true
    config:
      file: .rubocop_codeclimate.yml
```

With a setup like that, you can continue to get `.rubocop_todo.yml` applied
locally, but not on codeclimate.com.

I hope that explanation makes sense & is helpful to you. I'm going to go ahead
and close this, but if you further questions or run into any issues with the
setup I suggested, feel free to comment here and I'll get back to you.

**Comment by Br3nda** [comment]
Thanks for the  great reply. I couldn't find that in the  docs, and the
code climate support person sent me here to request the feature.

Could it be added to the docs for future reference?

On 3 Dec 2016 12:14 pm, "Will Fleming" <notifications@github.com> wrote:

Hi @Br3nda <https://github.com/Br3nda>,

Thanks for the suggestion, but we don't think this is a direction we want
to go
in right now for default behavior. In general, we think Code Climate engines
work best for people when they adhere as closely as possible to what the
same
tool would do when you ran it locally without Code Climate. In the case
you're
talking about, the .rubocop_todo.yml file is explicit configuration saying
that some RuboCop issues should be ignored, and we think it's best for this
engine to continue to respect that by default.

That said, this is behavior you can configure yourself today! You can move
the
bulk of your RuboCop configuration to a separate file (e.g.
.rubocop_codeclimate.yml), and then change your .rubocop.yml to have no
actual configuration except inheriting from .rubocop_codeclimate.yml and
.rubocop_todo.yml, e.g.

inherit_from: .rubocop_codeclimate.ymlinherit_from: .rubocop_todo.yml

Once you've done that, you can update your .codeclimate.yml to tell the
RuboCop engine to use .rubocop_codeclimate.yml for its configuration instead
of the default .rubocop.yml:

engines:
  rubocop:
    enabled: true
    config:
      file: .rubocop_codeclimate.yml

With a setup like that, you can continue to get .rubocop_todo.yml applied
locally, but not on codeclimate.com.

I hope that explanation makes sense & is helpful to you. I'm going to go
ahead
and close this, but if you further questions or run into any issues with the
setup I suggested, feel free to comment here and I'll get back to you.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/codeclimate/codeclimate-rubocop/issues/86#issuecomment-264588145>,
or mute the thread

**Comment by wfleming** [comment]
> Could it be added to the docs for future reference?

Yep, I thought we did mention the custom config file in the docs, but I guess we missed that. I'll update the page on docs.codeclimate.com today to mention this, thanks for the suggestion.

**Comment by Br3nda** [comment]
I tried this, and rubocop does not respect the second include. You only get one

**Comment by wfleming** [comment]
Oh, sorry, @Br3nda, that was poor proof-reading on my part. The correct syntax is to give `inherit_from` an array of filenames (docs at https://github.com/bbatsov/rubocop/blob/master/manual/configuration.md#inheriting-from-another-configuration-file-in-the-project).

Can you try that & see if it works better?
