### ISSUE TITLE
Configure Rubocop version via CircleCI configuration

### ISSUE THREAD

**Issue by damien** [codeclimate/codeclimate-rubocop#92]
Hey all,

First off, thanks for the awesome service! Super handy for keeping me and my teammates honest about our code quality.

That being said, it'd be great if we could specify which version of Rubocop this engine uses. My team is running a number of Rubocop-enabled projects with varying level of activity. Some of them are still on Rubocop versions as early as Rubocop v0.3x Allowing people to specify the version of Rubocop their project uses should help them avoid builds breaking due to upstream changes in this engine.

Thoughts? Comments? Let me know! I'd be more than happy to contribute to this project if the maintainers would be receptive to this change.

**Comment by damien** [comment]
A thought on a potential implementation: Have this engine scan the ruby project in question for a Gemfile. If one is present and includes Rubocop, use the bundled version of rubocop, otherwise default to the latest, stable version of Rubocop.

**Comment by maxjacobson** [comment]
Hi there. Depending which version of RuboCop you're using outside of Code Climate, we may already support it via [engine channels](https://docs.codeclimate.com/docs/engine-channels). We [currently](https://github.com/codeclimate/codeclimate-rubocop/branches/all?utf8=%E2%9C%93&query=channel%2Frubocop) offer these channels:

* `rubocop-0-42`
* `rubocop-0-46`
* `rubocop-0-48`
* `rubocop-0-49`

And we're planning to add a `rubocop-0-50` soon (see [tracking issue](https://github.com/codeclimate/codeclimate-rubocop/issues/107))

Long-term we may do something more automatic than this, but for the time being, please pick the channel that you prefer and feel free to let us know when we're missing support for things that you need.
