### ISSUE TITLE
Upgrade to latest Rubocop

### ISSUE THREAD

**Issue by claytron** [codeclimate/codeclimate-rubocop#96]
I have been seeing a lot of false positives lately in our code climate. Turns out this is because of rule changes in the latest Rubocop. Any plans on updating to the latest (0.48.1)?

**Comment by maxjacobson** [comment]
Hi @claytron. Please see this comment: https://github.com/codeclimate/codeclimate-rubocop/pull/91#issuecomment-302111401 and let me know if you have any questions

**Comment by claytron** [comment]
Thanks for the pointer!
