### ISSUE TITLE
bump default version to 0.49.1 (or greater)

### ISSUE THREAD

**Issue by olbrich** [codeclimate/codeclimate-rubocop#99]
There is an open CVE for rubocop versions less than 0.49.1.

see https://github.com/bbatsov/rubocop/issues/4336

**Comment by wassimk** [comment]
This would be great.

**Comment by wyefei** [comment]
Or create a channel for 0.49.1, please!

**Comment by InteNs** [comment]
any progress on this?
codeclimate seems to be contradicting local rubocop offences because of the version difference

**Comment by mbellgb** [comment]
Notably I'm receiving errors for mismatching `Style/PercentLiteralDelimiters` rules, something fixed in a more recent version of rubocop. bbatsov/rubocop#4039

**Comment by wassimk** [comment]
I saw chatter on the rails/rails repo this weekend about how the Rubocop config on CodeClimate is dated. Lack of this update is wasting a lot of time for folks. What gives?

**Comment by jondkinney** [comment]
One of the main reasons I'm _paying_ for CodeClimate for several people at my company is to have accurate rubocop on PRs. Please fix this soon! cc: @brynary

**Comment by brynary** [comment]
@olbrich @jondkinney et al. Thanks for bringing this to our attention. This appears to have fallen through a gap in our processes here and we're now teeing this up for engineering. We will post updates here.

**Comment by petergoldstein** [comment]
@brynary Any update on this?  It's been a week since your last comment.  Is there an ETA for when Rubocop 0.49.1 will be available?

**Comment by katwchen** [comment]
HI @petergoldstein, 
we started working on this, should have it done by next week. Thanks!

**Comment by katwchen** [comment]
This has been released, thanks to @pointlessone !

**Comment by deivid-rodriguez** [comment]
@katwchen You reopened this because the new channel still needs to be made available, right?

**Comment by pointlessone** [comment]
@deivid-rodriguez Yes. I will close this issue when the channel will be available on CC and in the CLI.

**Comment by deivid-rodriguez** [comment]
Ok, thank you! :heart:

**Comment by pointlessone** [comment]
`rubocop-0-49` channel is available both on CC and in CLI. It runs RuboCop 0.49.1.

**Comment by sullerandras** [comment]
How to get the updated version? When i use the `codeclimate` cli it still downloads a 3 month old `codeclimate-rubocop`, which has 0.46:
```
codeclimate/codeclimate-rubocop  latest  4aa21887caac  3 months ago  189MB
```

**Comment by maxjacobson** [comment]
@sullerandras 👋 hi there. Are you [explicitly setting your channel to `rubocop-0-49`](https://docs.codeclimate.com/docs/rubocop#section-using-rubocop-s-newer-versions)?
